/**
 * 큰 파일(10000줄+) 합성 생성기 — region 입력 품질을 "스케일에서" 측정하기 위한 결정론 픽스처.
 *
 * 왜 합성인가:
 *  - eval-fixtures/*.tsx 는 실고객 코드라 .gitignore 로 커밋 제외된다. 큰 파일을 거기 떨구면
 *    저장소에 남길 수 없고 재현도 안 된다. 대신 **스캐폴드 스타일을 본뜬 결정론 생성기**(이 파일,
 *    커밋됨)로 매번 동일한 큰 파일을 메모리에서 만든다 — 고객 코드 유출 0, 재현 100%.
 *  - 작은 픽스처(250~440줄)로 튜닝된 locate/depsHeader 로직이 10000줄에서 무너지는 3가지
 *    (①depsHeader 폭주 ②앵커 오타깃 ③섹션 라우팅 부재)를 자극하도록 구조를 짠다:
 *     · 한 개의 거대 default-export 컴포넌트(= god component) 안에 N개 도메인 섹션을 쌓는다.
 *     · 섹션마다 고유 한글 앵커(섹션 주석 + SelectValue placeholder)를 박아 "의도한 섹션"을
 *       ground-truth(manifest)로 안다 → region이 그 줄 범위에 떨어졌는지 채점 가능.
 *     · 섹션마다 top-level 타입 2개 + 옵션 const 1개를 둬 depsHeader 가 모든 타입을 무차별로
 *       담는 ① 폭주를 재현한다(대부분 타입은 한 섹션만 참조 = 무관).
 *
 * 외부 의존성 0. 출력은 valid-ish TSX 텍스트(파서가 아닌 문자열/들여쓰기 기반 locate 대상).
 */

/** 도메인 [한글라벨, 영문식별자] 쌍. 한글 토큰은 섹션 유일 앵커, 영문은 식별자/엔드포인트용. */
const DOMAINS: ReadonlyArray<readonly [string, string]> = [
  ['부서', 'dept'], ['직원', 'employee'], ['프로젝트', 'project'], ['근태', 'attendance'],
  ['휴가', 'leave'], ['급여', 'payroll'], ['교육', 'training'], ['자격증', 'license'],
  ['평가', 'evaluation'], ['조직', 'org'], ['발령', 'assignment'], ['출장', 'travel'],
  ['경비', 'expense'], ['자산', 'asset'], ['회의실', 'room'], ['공지', 'notice'],
  ['문서', 'document'], ['결재', 'approval'], ['거래처', 'client'], ['계약', 'contract'],
  ['매출', 'sales'], ['구매', 'purchase'], ['재고', 'inventory'], ['품질', 'quality'],
  ['생산', 'production'], ['설비', 'equipment'], ['안전', 'safety'], ['민원', 'complaint'],
  ['고객', 'customer'], ['마케팅', 'marketing'], ['영업', 'biz'], ['회계', 'accounting'],
  ['예산', 'budget'], ['세무', 'tax'], ['감사', 'audit'], ['법무', 'legal'],
  ['보안', 'security'], ['전산', 'it'], ['네트워크', 'network'], ['서버', 'server'],
  ['데이터', 'dataset'], ['백업', 'backup'], ['라이선스', 'licenseKey'], ['권한', 'permission'],
  ['메뉴', 'menu'], ['코드', 'commonCode'], ['배치', 'batch'], ['로그', 'log'],
  ['알림', 'alert'], ['메일', 'mail'], ['게시판', 'board'], ['댓글', 'comment'],
  ['첨부', 'attach'], ['이미지', 'image'], ['동영상', 'video'], ['통계', 'stat'],
  ['리포트', 'report'], ['대시보드', 'dashboard'], ['캘린더', 'calendar'], ['일정', 'schedule'],
  ['연락처', 'phone'], ['주소록', 'addrbook'], ['즐겨찾기', 'favorite'], ['설정', 'setting'],
] as const;

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

export interface SectionManifest {
  /** 0-based 섹션 인덱스 */
  index: number;
  /** 한글 도메인 라벨(쿼리 유일 앵커) */
  ko: string;
  /** 영문 식별자 */
  en: string;
  /** 섹션 JSX 블록 시작 줄(섹션 주석, 1-based, 포함) */
  startLine: number;
  /** 섹션 JSX 블록 끝 줄(닫는 </Card>, 1-based, 포함) */
  endLine: number;
  /** 이 섹션의 상태 Select 여는 줄(1-based) */
  selectLine: number;
  /** 이 섹션의 table 여는 줄(1-based) */
  tableLine: number;
}

export interface LargeFile {
  /** 합성된 전체 파일 텍스트 */
  source: string;
  /** 섹션별 ground-truth 앵커 */
  manifest: SectionManifest[];
  /** 총 줄 수 */
  lineCount: number;
}

/**
 * N개 도메인 섹션을 가진 거대 단일 컴포넌트 파일을 생성한다.
 * @param sectionCount 섹션 수(기본 64 = DOMAINS 전체 ≈ 10000줄). DOMAINS 길이로 클램프.
 */
export function generateLargeFile(sectionCount = DOMAINS.length): LargeFile {
  const n = Math.max(1, Math.min(sectionCount, DOMAINS.length));
  const out: string[] = [];
  const push = (s = ''): number => out.push(s); // out.length === 다음 줄 번호(1-based) 직전
  const lineNo = (): number => out.length + 1; // 다음에 push할 줄의 1-based 번호

  // ── import ──
  push(`// [AUTO-GENERATED by scripts/synth-large-file.ts — 큰 파일 측정용 합성 픽스처]`);
  push(`import { useApi } from '@axiom/hooks';`);
  push(
    `import { Button, Card, CardContent, CardHeader, CardTitle, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@axiom/components/ui';`,
  );
  push(`import { useEffect, useState } from 'react';`);
  push();

  // ── 공통 타입 ──
  push(`/** 상태 옵션 공통 타입 */`);
  push(`type TStatusOption = { value: string; label: string };`);
  push();

  // ── 섹션별 top-level 타입 + 엔드포인트(① depsHeader 폭주의 원천) ──
  for (let i = 0; i < n; i++) {
    const [ko, en] = DOMAINS[i];
    const P = cap(en);
    push(`// ${ko}관리 행 타입`);
    push(`type T${P}Row = {`);
    push(`\tid: number;`);
    push(`\tname: string;`);
    push(`\tstatus: 'active' | 'pending' | 'done';`);
    push(`\towner: string;`);
    push(`\tamount: number;`);
    push(`\tupdated_at: string;`);
    push(`};`);
    push(`type T${P}Response = { success: boolean; data: T${P}Row[]; total: number };`);
    push(`const ${en.toUpperCase()}_ENDPOINT = '/api/${en.toLowerCase()}';`);
    push();
  }

  // ── 컴포넌트 시작 ──
  push(`export default function MegaDashboardPage(): React.ReactNode {`);

  // 섹션별 state + 훅 + 파생 const + 옵션 배열(② return 전 hook 블록을 거대하게 만듦) ──
  for (let i = 0; i < n; i++) {
    const [ko, en] = DOMAINS[i];
    const P = cap(en);
    push(`\t/** ${ko}관리 — 선택 상태 + 서버 조회 */`);
    push(`\tconst [selected${P}, setSelected${P}] = useState<string>('all');`);
    push(`\tconst [search${P}, setSearch${P}] = useState<string>('');`);
    push(
      `\tconst { data: ${en}Resp, isPending: ${en}Pending } = useApi<T${P}Response>(${en.toUpperCase()}_ENDPOINT, {`,
    );
    push(`\t\tparams: { status: selected${P} === 'all' ? undefined : selected${P}, q: search${P} || undefined },`);
    push(`\t});`);
    push(`\tconst ${en}Rows = ${en}Resp?.data ?? [];`);
    push(`\tconst ${en}StatusOptions: TStatusOption[] = [`);
    push(`\t\t{ value: 'all', label: '전체' },`);
    push(`\t\t{ value: 'active', label: '진행' },`);
    push(`\t\t{ value: 'pending', label: '대기' },`);
    push(`\t\t{ value: 'done', label: '완료' },`);
    push(`\t];`);
    push();
  }

  // ── return / JSX ──
  push(`\treturn (`);
  push(`\t\t<div className="p-5 space-y-6">`);

  const manifest: SectionManifest[] = [];
  for (let i = 0; i < n; i++) {
    const [ko, en] = DOMAINS[i];
    const P = cap(en);
    const startLine = lineNo(); // 섹션 주석 줄
    push(`\t\t\t{/* ===== 섹션 ${String(i + 1).padStart(2, '0')}: ${ko}관리 ===== */}`);
    push(`\t\t\t<Card className="border shadow-sm">`);
    push(`\t\t\t\t<CardHeader>`);
    push(`\t\t\t\t\t<CardTitle>${ko}관리</CardTitle>`);
    push(`\t\t\t\t</CardHeader>`);
    push(`\t\t\t\t<CardContent className="space-y-4">`);
    push(`\t\t\t\t\t<div className="flex flex-wrap gap-2">`);
    const selectLine = lineNo();
    push(`\t\t\t\t\t\t<Select value={selected${P}} onValueChange={setSelected${P}}>`);
    push(`\t\t\t\t\t\t\t<SelectTrigger className="w-44">`);
    push(`\t\t\t\t\t\t\t\t<SelectValue placeholder="${ko} 상태 선택" />`);
    push(`\t\t\t\t\t\t\t</SelectTrigger>`);
    push(`\t\t\t\t\t\t\t<SelectContent>`);
    push(`\t\t\t\t\t\t\t\t{${en}StatusOptions.map((opt) => (`);
    push(`\t\t\t\t\t\t\t\t\t<SelectItem key={opt.value} value={opt.value}>`);
    push(`\t\t\t\t\t\t\t\t\t\t{opt.label}`);
    push(`\t\t\t\t\t\t\t\t\t</SelectItem>`);
    push(`\t\t\t\t\t\t\t\t))}`);
    push(`\t\t\t\t\t\t\t</SelectContent>`);
    push(`\t\t\t\t\t\t</Select>`);
    push(`\t\t\t\t\t\t<Input`);
    push(`\t\t\t\t\t\t\tclassName="h-9 w-48"`);
    push(`\t\t\t\t\t\t\tvalue={search${P}}`);
    push(`\t\t\t\t\t\t\tonChange={(e) => setSearch${P}(e.target.value)}`);
    push(`\t\t\t\t\t\t\tplaceholder="${ko} 검색..."`);
    push(`\t\t\t\t\t\t/>`);
    push(`\t\t\t\t\t\t<Button size="sm">${ko} 등록</Button>`);
    push(`\t\t\t\t\t</div>`);
    const tableLine = lineNo();
    push(`\t\t\t\t\t<table className="w-full text-sm">`);
    push(`\t\t\t\t\t\t<thead>`);
    push(`\t\t\t\t\t\t\t<tr>`);
    push(`\t\t\t\t\t\t\t\t<th className="text-left">이름</th>`);
    push(`\t\t\t\t\t\t\t\t<th className="text-left">상태</th>`);
    push(`\t\t\t\t\t\t\t\t<th className="text-left">담당자</th>`);
    push(`\t\t\t\t\t\t\t\t<th className="text-right">금액</th>`);
    push(`\t\t\t\t\t\t\t\t<th className="text-left">수정일</th>`);
    push(`\t\t\t\t\t\t\t</tr>`);
    push(`\t\t\t\t\t\t</thead>`);
    push(`\t\t\t\t\t\t<tbody>`);
    push(`\t\t\t\t\t\t\t{${en}Rows.map((row) => (`);
    push(`\t\t\t\t\t\t\t\t<tr key={row.id} className="border-t">`);
    push(`\t\t\t\t\t\t\t\t\t<td>{row.name}</td>`);
    push(`\t\t\t\t\t\t\t\t\t<td>{row.status}</td>`);
    push(`\t\t\t\t\t\t\t\t\t<td>{row.owner}</td>`);
    push(`\t\t\t\t\t\t\t\t\t<td className="text-right">{row.amount.toLocaleString()}</td>`);
    push(`\t\t\t\t\t\t\t\t\t<td>{row.updated_at}</td>`);
    push(`\t\t\t\t\t\t\t\t</tr>`);
    push(`\t\t\t\t\t\t\t))}`);
    push(`\t\t\t\t\t\t\t{${en}Pending && (`);
    push(`\t\t\t\t\t\t\t\t<tr>`);
    push(`\t\t\t\t\t\t\t\t\t<td colSpan={5}>불러오는 중…</td>`);
    push(`\t\t\t\t\t\t\t\t</tr>`);
    push(`\t\t\t\t\t\t\t)}`);
    push(`\t\t\t\t\t\t</tbody>`);
    push(`\t\t\t\t\t</table>`);
    push(`\t\t\t\t</CardContent>`);
    push(`\t\t\t</Card>`);

    // 요약 카드 — 섹션 부피를 실제 대시보드 수준으로 키운다(파일 10000줄+ 확보).
    push(`\t\t\t<Card className="border shadow-sm">`);
    push(`\t\t\t\t<CardHeader>`);
    push(`\t\t\t\t\t<CardTitle>${ko} 요약</CardTitle>`);
    push(`\t\t\t\t</CardHeader>`);
    push(`\t\t\t\t<CardContent>`);
    push(`\t\t\t\t\t<div className="grid grid-cols-4 gap-3">`);
    for (const [tileLabel, tileExpr] of [
      ['전체', `${en}Rows.length`],
      ['진행', `${en}Rows.filter((r) => r.status === 'active').length`],
      ['대기', `${en}Rows.filter((r) => r.status === 'pending').length`],
      ['완료', `${en}Rows.filter((r) => r.status === 'done').length`],
    ] as const) {
      push(`\t\t\t\t\t\t<div className="rounded border p-3">`);
      push(`\t\t\t\t\t\t\t<div className="text-xs text-muted-foreground">${ko} ${tileLabel}</div>`);
      push(`\t\t\t\t\t\t\t<div className="text-2xl font-semibold">{${tileExpr}}</div>`);
      push(`\t\t\t\t\t\t</div>`);
    }
    push(`\t\t\t\t\t</div>`);
    push(`\t\t\t\t</CardContent>`);
    push(`\t\t\t</Card>`);

    // 상세 카드 — 정의 리스트로 섹션 부피를 키운다(파일 10000줄+ 확보).
    push(`\t\t\t<Card className="border shadow-sm">`);
    push(`\t\t\t\t<CardHeader>`);
    push(`\t\t\t\t\t<CardTitle>${ko} 상세</CardTitle>`);
    push(`\t\t\t\t</CardHeader>`);
    push(`\t\t\t\t<CardContent>`);
    push(`\t\t\t\t\t<dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">`);
    for (const field of ['담당부서', '책임자', '등록일', '수정일', '상태코드', '비고', '연락처', '분류', '우선순위', '진척률', '예산코드', '승인자']) {
      push(`\t\t\t\t\t\t<div className="flex justify-between border-b py-1">`);
      push(`\t\t\t\t\t\t\t<dt className="text-muted-foreground">${ko} ${field}</dt>`);
      push(`\t\t\t\t\t\t\t<dd>{${en}Rows[0]?.name ?? '-'}</dd>`);
      push(`\t\t\t\t\t\t</div>`);
    }
    push(`\t\t\t\t\t</dl>`);
    push(`\t\t\t\t</CardContent>`);
    const endLine = lineNo(); // 닫는 </Card>(섹션의 마지막 카드)
    push(`\t\t\t</Card>`);
    push();

    manifest.push({ index: i, ko, en, startLine, endLine, selectLine, tableLine });
  }

  push(`\t\t</div>`);
  push(`\t);`);
  push(`}`);

  const source = out.join('\n');
  return { source, manifest, lineCount: out.length };
}
